name: Build Siti Remote
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build with Buildozer
        # Corrected the spelling of the action repository
        uses: ArtemSerebrennikov/buildozer-action@v1
        with:
          buildozer_version: master
          workdir: .

      - name: Upload APK
        # Updated to v4 to fix the deprecation error in your log
        uses: actions/upload-artifact@v4
        with:
          name: SitiRemote-App
          path: bin/*.apk
          
